/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:48ffdfb8-ff3e-4d9f-835b-7529c363cf6a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_NDhOXTT6E",
    "aws_user_pools_web_client_id": "4e9sdbihdktlaovjqa15b8hlee",
    "oauth": {
        "domain": "oneqprodec842553-ec842553-sampledev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://master.d1i2ha05cazkpa.amplifyapp.com/signin/",
        "redirectSignOut": "https://master.d1i2ha05cazkpa.amplifyapp.com/signout/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "oneq-prod163137-sampledev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://xm2z3gk7t5denhrv3lkpa3xujm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
